spring:
  application:
    name: OficinaAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgresql://oficina_user:MfR8hxkYuYuug7CcxWIW1d90Gseww2l5@dpg-d7tkc61j2pic73adii4g-a/oficina_haiy
    username: oficina_user
    password: MfR8hxkYuYuug7CcxWIW1d90Gseww2l5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    OficinaAPI: DEBUG
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    use-root-path: true