spring:
  application:
    name: OficinaAPI
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL:update}
    show-sql: false
    open-in-view: false
    database-platform: ${DB_PLATFORM}
logging:
  level:
    OficinaAPI: DEBUG
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    use-root-path: true